In [1]:
# 03_model_explainability.ipynb
import os
import sys
sys.path.append('..')
import pandas as pd
import joblib

from src.shap_interpretation import (
    explain_xgb_with_shap,
    explain_logreg_with_shap
)

# ========== Credit Card Fraud ==========

# Load data and models
# ========== Credit Card Fraud ==========

# Load credit card data and models
df_cc = pd.read_csv("../data/raw/creditcard.csv")  # <- FIXED
xgb_cc = joblib.load("../models/xgboost_creditcard_fraud.pkl")
logreg_cc = joblib.load("../models/logisticregression_creditcard_fraud.pkl")

X_cc = df_cc.drop(columns=["Class"])
features_cc = X_cc.columns.tolist()

# SHAP for XGBoost
explain_xgb_with_shap(xgb_cc, X_cc, features_cc, dataset_name="creditcard", sample_index=5)

# SHAP for Logistic Regression
explain_logreg_with_shap(logreg_cc, X_cc, features_cc, dataset_name="creditcard", sample_index=5)

# ========== E-Commerce Fraud ==========



c:\Users\tsega\OneDrive\Documents\-detection-of-fraud-cases-for-e-commerce\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
100%|===================| 284801/284807 [14:15<00:00]        

.values =
array([[ 4.80711216e+04, -2.60563453e+00,  7.18395201e-02, ...,
        -2.72340886e-02,  6.21830342e-03,  8.58709273e+01],
       [ 4.80711216e+04,  2.02661817e+00,  3.75982560e-01, ...,
        -4.94040459e-03,  1.84436105e-02, -2.47728097e+02],
       [ 4.80706172e+04, -2.60299665e+00, -1.06545502e+00, ...,
         2.31187983e-03, -7.00532108e-03,  6.05897611e+02],
       ...,
       [-3.90836502e+04,  3.34768809e+00, -1.33182126e-01, ...,
        -7.04210625e-03,  4.33626124e-03, -9.97166605e+01],
       [-3.90836502e+04, -5.73552446e-01,  6.13182660e-01, ...,
        -2.33650872e-02,  4.91318047e-02, -2.31131018e+02],
       [-3.90856678e+04, -1.10541024e+00, -3.31083709e-02, ...,
        -5.96761609e-03,  1.80761890e-02,  2.38854677e+02]],
      shape=(284807, 30))

.base_values =
array([-47822.35128611, -47822.35128611, -47822.35128611, ...,
       -47822.35128611, -47822.35128611, -47822.35128611], shape=(284807,))

.data =
array([[ 0.00000000e+00, -1.35980713e+00, -

<Figure size 800x950 with 0 Axes>

<Figure size 800x950 with 0 Axes>

<Figure size 2000x300 with 0 Axes>

In [3]:
df_ec = pd.read_csv("../data/processed/transformed_train.csv")
xgb_ec = joblib.load("../models/xgboost_ecommerce_fraud.pkl")
logreg_ec = joblib.load("../models/logisticregression_ecommerce_fraud.pkl")

X_ec = df_ec.drop(columns=["class"])
features_ec = X_ec.columns.tolist()

# SHAP for XGBoost
explain_xgb_with_shap(xgb_ec, X_ec, features_ec, dataset_name="ecommerce", sample_index=5)

# SHAP for Logistic Regression
explain_logreg_with_shap(logreg_ec, X_ec, features_ec, dataset_name="ecommerce", sample_index=5)

100%|===================| 218683/219136 [07:15<00:00]        

.values =
array([[-8.04331848e-04,  1.28245119e-03,  9.25605190e-01, ...,
        -7.95338600e-03, -7.95338600e-03,  0.00000000e+00],
       [ 2.28257884e-03, -2.44726230e-04, -1.53432237e+00, ...,
         5.30225733e-03,  5.30225733e-03,  0.00000000e+00],
       [-2.24489017e-03,  2.80962862e-03, -1.26064015e+00, ...,
         5.30225733e-03,  5.30225733e-03,  0.00000000e+00],
       ...,
       [-5.37621347e-03,  1.86917604e-03, -7.56605981e-02, ...,
         5.30225733e-03,  5.30225733e-03,  0.00000000e+00],
       [-8.84551217e-04,  1.45523184e-03, -1.54046852e+00, ...,
        -7.95338600e-03, -7.95338600e-03,  0.00000000e+00],
       [ 3.42420929e-03,  4.93207034e-03,  5.96465349e-01, ...,
         5.30225733e-03,  5.30225733e-03,  0.00000000e+00]],
      shape=(219136, 15))

.base_values =
array([0.3567868, 0.3567868, 0.3567868, ..., 0.3567868, 0.3567868,
       0.3567868], shape=(219136,))

.data =
array([[ 0.16551491,  0.33202922, -1.42592488, ...,  1.        ,
         0.   